### ISSUE TITLE
ImportError: cannot import name 'MoeCausalLMOutputWithPast' from 'transformers.modeling_outputs' (/home/ubuntu/EAGLE/eagle/lib/python3.10/site-packages/transformers/modeling_outputs.py

### ISSUE THREAD

**Issue by S-Yacer** [SafeAILab/EAGLE#33]
#!/bin/bash

# Assign fixed values to variables
EA_MODEL_PATH='yuhuili/EAGLE-mixtral-instruct-8x7B'
BASE_MODEL_PATH='mistralai/Mixtral-8x7B-v0.1'
MODEL_TYPE='mixtral'

# Run the application with the specified arguments
python3 -m application.webui --ea-model-path $EA_MODEL_PATH \
		--base-model-path $BASE_MODEL_PATH \
		--model-type $MODEL_TYPE
		
		
error: ImportError: cannot import name 'MoeCausalLMOutputWithPast' from 'transformers.modeling_outputs' (/home/ubuntu/EAGLE/eagle/lib/python3.10/site-packages/transformers/modeling_outputs.py

**Comment by S-Yacer** [comment]
also files for gpt-fast conversion are lacking such as convert_hf_checkpoint_EAGLE.py

**Comment by Liyuhui-12** [comment]
> error: ImportError: cannot import name 'MoeCausalLMOutputWithPast' from 'transformers.modeling_outputs' (/home/ubuntu/EAGLE/eagle/lib/python3.10/site-packages/transformers/modeling_outputs.py

This is due to the transformers package being of a lower version. You can use transformers==4.36.2. We have already updated the requirements.txt.

**Comment by Liyuhui-12** [comment]
>convert_hf_checkpoint_EAGLE.py and convert_hf_checkpoint.py

Thanks for the reminder, they are now available.

**Comment by S-Yacer** [comment]
thanks for the prompt response ! but I am encountering a new issue when running the inference scripts for the webui:

pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 1.63G/1.63G [00:05<00:00, 321MB/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/EAGLE/application/webui.py", line 246, in <module>
    warmup(model)
  File "/home/ubuntu/EAGLE/application/webui.py", line 90, in warmup
    input_ids = torch.as_tensor(input_ids).cuda()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available


Nvidia-smi works, showing my 2 A100 gpus as well as nvcc -V that displayed cuda_12.1. Using cuda.is_available() yields true..

**Comment by S-Yacer** [comment]
thank you ! the webui works.. ive noticed that the ea layer isnt optimised for mixtral, seems that the architecture is for llama... will the ea layer for mixtral be optimised ? (i see little speedup when using eagle and inferring with mixtral series models, for reference i used the ea weights given in the repo for mixtral instruct).

**Comment by hongyanz** [comment]
We haven't tried to optimize the architecture of EAGLE layer yet for Mixtral due to the time issue. There should be significant room to improve here by changing the EAGLE layer to the Mixtral-like architecture. We will explore it as our next step.

**Comment by S-Yacer** [comment]
thank you for the great contribution ^^.. will look forward to the next steps of this repo..
small question, does gpt-fast support mixtral or is it solely for llama?

**Comment by hongyanz** [comment]
gpt-fast does support mixtral, but not very well. For example, they only support int8 quantization (not int4) for mixtral, and they do not support multi-gpu running (at least, we have tried but failed). This means only A100/H100 (80G) can support the running of gpt-fast for mixtral.

**Comment by S-Yacer** [comment]
a little update, i was able to run mixtral on multi-gpu using gpt-fast, following this pull: https://github.com/yanboliang/gpt-fast/tree/mixtral-moe fp16 and int8 loaded fine on x2 A100s. Will try eagle on top and see how far the speed up can be ^-^.

**Comment by hongyanz** [comment]
Great. Thank you!
